'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Menu, X, MessageCircle, Mail, Phone, Star, ChevronDown, Send } from 'lucide-react';
import { allDestinations, company, faqs, interestTours, packages, posts, services, trust } from '@/lib/data';

const nav = [['Home','/'],['About','/about'],['Services','/services'],['Tour Packages','/tour-packages'],['Destinations','/destinations'],['Contact','/contact']];
const fade = { initial: { opacity: 0, y: 24 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { duration: .55 } };

export function Header(){ const [open,setOpen]=useState(false); return <header className="sticky top-0 z-50 border-b border-white/10 bg-navy/95 text-white backdrop-blur"><div className="container flex h-20 items-center justify-between"><Link href="/" className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-gold font-black text-navy">JST</span><span><strong className="block leading-tight">Jaladhi Setu Travel</strong><small className="text-white/70">Your Gateway to India and Beyond</small></span></Link><nav className="hidden items-center gap-7 text-sm font-medium lg:flex">{nav.map(([n,h])=><Link key={h} href={h} className="hover:text-gold">{n}</Link>)}<Link href="/contact" className="btn-primary py-2.5">Get a Quote</Link></nav><button aria-label="Open menu" onClick={()=>setOpen(!open)} className="lg:hidden">{open?<X/>:<Menu/>}</button></div><AnimatePresence>{open&&<motion.div initial={{height:0}} animate={{height:'auto'}} exit={{height:0}} className="overflow-hidden lg:hidden"><div className="container grid gap-3 pb-6">{nav.map(([n,h])=><Link onClick={()=>setOpen(false)} key={h} href={h} className="rounded-xl bg-white/10 px-4 py-3">{n}</Link>)}</div></motion.div>}</AnimatePresence></header> }

export function Footer(){ return <footer className="bg-navy text-white"><Newsletter/><div className="container grid gap-10 py-12 md:grid-cols-4"><div><div className="mb-4 text-2xl font-black text-gold">JST</div><p className="text-white/70">Premium travel planning for Mauritian travelers exploring India and beyond.</p></div><div><h3 className="font-bold">Explore</h3>{nav.map(([n,h])=><Link key={h} href={h} className="mt-3 block text-white/70 hover:text-gold">{n}</Link>)}</div><div><h3 className="font-bold">Contact</h3><p className="mt-3 text-white/70">{company.phone}</p><p className="text-white/70">{company.email}</p><p className="text-white/70">{company.website}</p></div><div><h3 className="font-bold">Travel Focus</h3><p className="mt-3 text-white/70">India tours, flights, visas, hotels, pilgrimage, hill stations, family and luxury travel.</p></div></div><div className="border-t border-white/10 py-5 text-center text-sm text-white/60">© 2026 Jaladhi Setu Travel. All rights reserved.</div></footer> }

export function FloatingWhatsApp(){ return <a aria-label="WhatsApp JST" href={company.whatsapp} className="fixed bottom-5 right-5 z-50 flex h-14 w-14 items-center justify-center rounded-full bg-green-500 text-white shadow-2xl transition hover:scale-105"><MessageCircle/></a> }

export function ExitIntent(){ const [show,setShow]=useState(false); useEffect(()=>{const f=(e:MouseEvent)=>{if(e.clientY<8&&!sessionStorage.getItem('exitJst')){sessionStorage.setItem('exitJst','1');setShow(true)}}; document.addEventListener('mouseleave',f); return()=>document.removeEventListener('mouseleave',f)},[]); return <AnimatePresence>{show&&<Modal title="Free Travel Consultation" onClose={()=>setShow(false)}><p className="mb-5 text-slate-600">Before you go, claim a free personalized itinerary consultation for your India trip.</p><LeadForm compact/></Modal>}</AnimatePresence> }

export function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){ return <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[60] grid place-items-center bg-navy/70 p-4 backdrop-blur"><motion.div initial={{scale:.95,y:20}} animate={{scale:1,y:0}} exit={{scale:.95,y:20}} className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-3xl bg-white p-6 shadow-2xl"><div className="mb-4 flex items-center justify-between"><h2 className="text-2xl font-black text-navy">{title}</h2><button aria-label="Close" onClick={onClose}><X/></button></div>{children}</motion.div></motion.div> }

export function LeadForm({compact=false}:{compact?:boolean}){ return <form className="grid gap-4 md:grid-cols-2"><input className="input" placeholder="Full name" aria-label="Full name"/><input className="input" placeholder="Email address" type="email" aria-label="Email"/><input className="input" placeholder="Phone / WhatsApp" aria-label="Phone"/><select className="input" aria-label="Travel interest"><option>Travel interest</option><option>Flights</option><option>Visa Assistance</option><option>Hotels</option><option>Tour Packages</option><option>Travel Insurance</option></select>{!compact&&<textarea className="input md:col-span-2" rows={5} placeholder="Tell us about your trip" aria-label="Message"/>}<button type="button" className="btn-primary md:col-span-2"><Send className="mr-2 h-4 w-4"/> Get a Personalized Quote</button></form> }

export function Newsletter(){ return <section className="border-b border-white/10 bg-blue py-6"><div className="container flex flex-col items-center gap-4 md:flex-row md:justify-between"><div><h2 className="text-xl font-bold text-white">Get India travel ideas and exclusive quote support</h2><p className="text-white/70">Join JST updates for Mauritian travelers.</p></div><div className="flex w-full gap-2 md:w-auto"><input className="input min-w-0" placeholder="Email address"/><button className="btn-primary whitespace-nowrap">Subscribe</button></div></div></section> }

export function Hero(){ const tabs=['Flights','Hotels','Visa Assistance','Tour Packages','Travel Insurance']; const [tab,setTab]=useState(tabs[0]); return <section className="relative overflow-hidden bg-navy text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_20%,rgba(214,168,79,.25),transparent_35%),linear-gradient(135deg,#08264A,#0D3B66)]"/><div className="container relative grid gap-10 py-20 lg:grid-cols-[1.1fr_.9fr] lg:py-28"><motion.div {...fade}><p className="mb-4 font-semibold text-gold">{company.tagline}</p><h1 className="text-4xl font-black leading-tight md:text-6xl">Explore India with Confidence</h1><p className="mt-6 max-w-2xl text-lg text-white/80">Flights, Visa Assistance, Hotels, and Personalized Tour Packages for Mauritian Travelers.</p><div className="mt-8 flex flex-wrap gap-4"><a href="#contact" className="btn-primary">Get a Personalized Quote</a><Link href="/contact" className="btn-secondary">Contact Us</Link></div></motion.div><motion.div {...fade} className="rounded-[2rem] bg-white p-4 text-ink shadow-2xl"><div className="flex gap-2 overflow-x-auto pb-3">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-bold ${tab===t?'bg-navy text-white':'bg-mist text-slate-600'}`}>{t}</button>)}</div><h2 className="mb-4 text-xl font-black text-navy">{tab} Inquiry</h2><LeadForm compact/></motion.div></div></section> }

export function ServicesGrid({detailed=false}:{detailed?:boolean}){ return <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{services.map(s=>{const Icon=s.icon; return <motion.article {...fade} key={s.title} className="card"><Icon className="mb-5 h-10 w-10 text-gold"/><h3 className="text-xl font-black text-navy">{s.title}</h3><p className="mt-3 text-slate-600">{detailed?s.details:s.desc}</p>{detailed&&<div className="mt-5"><LeadForm compact/></div>}<Link href="/services" className="mt-5 inline-block font-bold text-blue hover:text-gold">Learn More</Link></motion.article>})}</div> }

export function DestinationCards({groups=allDestinations}:{groups?:typeof allDestinations}){ const [dest,setDest]=useState<string|null>(null); return <>{groups.map(g=><section key={g.region} className="mb-12"><h3 className="mb-6 text-2xl font-black text-navy">{g.region}</h3><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{g.items.map(d=><motion.article {...fade} key={d} className="overflow-hidden rounded-3xl bg-white shadow-soft"><div role="img" aria-label={`${d} travel destination`} className="h-44 bg-gradient-to-br from-blue to-gold/70"/><div className="p-5"><h4 className="text-xl font-black text-navy">{d}</h4><button onClick={()=>setDest(d)} className="mt-4 btn-primary w-full py-2.5">Inquire Now</button></div></motion.article>)}</div></section>)}{dest&&<Modal title={`Plan your trip to ${dest}`} onClose={()=>setDest(null)}><LeadForm/></Modal>}</> }

export function PackageCards({all=false}:{all?:boolean}){ const [pkg,setPkg]=useState<any>(null); const list=all?packages:packages.slice(0,2); return <><div className="grid gap-6 lg:grid-cols-2">{list.map(p=><motion.article {...fade} key={p.title} className="card overflow-hidden"><p className="font-bold text-gold">{p.category} • {p.days}</p><h3 className="mt-2 text-3xl font-black text-navy">{p.title}</h3><p className="mt-4 text-slate-600">Route: {p.route.join(' → ')}</p><div className="mt-5 flex flex-wrap gap-2">{p.highlights.map((h:string)=><span key={h} className="rounded-full bg-mist px-3 py-1 text-sm font-semibold text-blue">{h}</span>)}</div><button onClick={()=>setPkg(p)} className="mt-6 btn-primary">Inquire Now</button></motion.article>)}</div>{pkg&&<Modal title={pkg.title} onClose={()=>setPkg(null)}><p className="font-semibold text-gold">{pkg.days}</p><h3 className="mt-4 font-bold text-navy">Route</h3><p className="text-slate-600">{pkg.route.join(' → ')}</p><h3 className="mt-4 font-bold text-navy">Inclusions</h3><ul className="mb-6 mt-2 grid gap-2">{pkg.inclusions.map((i:string)=><li key={i} className="rounded-xl bg-mist px-4 py-2">{i}</li>)}</ul><LeadForm compact/></Modal>}</> }

export function InterestTours(){ return <div className="grid gap-6 lg:grid-cols-3">{interestTours.map(t=><motion.article {...fade} key={t.title} className="rounded-3xl bg-navy p-7 text-white"><h3 className="text-2xl font-black text-gold">{t.title}</h3><div className="mt-5 flex flex-wrap gap-2">{t.places.map(p=><span key={p} className="rounded-full bg-white/10 px-3 py-1 text-sm">{p}</span>)}</div></motion.article>)}</div> }

export function TrustGrid(){ return <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-5">{trust.map(t=>{const Icon=t.icon; return <motion.article {...fade} className="card text-center" key={t.title}><Icon className="mx-auto mb-4 h-9 w-9 text-gold"/><h3 className="font-black text-navy">{t.title}</h3><p className="mt-2 text-sm text-slate-600">{t.desc}</p></motion.article>})}</div> }

export function Testimonials(){ const names=['Anisha, Port Louis','Rajen, Curepipe','Meera, Quatre Bornes','Vikash, Vacoas']; return <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">{names.map((n,i)=><motion.article {...fade} key={n} className="card"><div className="mb-4 h-16 w-16 rounded-full bg-gradient-to-br from-blue to-gold" role="img" aria-label={`${n} customer photo placeholder`}/><div className="flex text-gold">{[1,2,3,4,5].map(s=><Star key={s} className="h-4 w-4 fill-current"/>)}</div><p className="mt-4 text-slate-600">JST made our India journey smooth, comfortable, and perfectly planned from Mauritius.</p><h3 className="mt-4 font-black text-navy">{n}</h3></motion.article>)}</div> }

export function FAQ(){ const [open,setOpen]=useState(0); return <div className="mx-auto max-w-3xl divide-y divide-slate-200 rounded-3xl bg-white shadow-soft">{faqs.map(([q,a],i)=><div key={q} className="p-5"><button onClick={()=>setOpen(open===i?-1:i)} className="flex w-full items-center justify-between text-left font-bold text-navy">{q}<ChevronDown className={`${open===i?'rotate-180':''} transition`}/></button>{open===i&&<p className="mt-3 text-slate-600">{a}</p>}</div>)}</div> }

export function BlogPreview(){ return <div className="grid gap-6 md:grid-cols-3">{posts.map(p=><motion.article {...fade} key={p.title} className="overflow-hidden rounded-3xl bg-white shadow-soft"><div className="h-44 bg-gradient-to-br from-navy via-blue to-gold" role="img" aria-label={`${p.title} image placeholder`}/><div className="p-6"><span className="rounded-full bg-gold/20 px-3 py-1 text-sm font-bold text-blue">{p.category}</span><h3 className="mt-4 text-xl font-black text-navy">{p.title}</h3><p className="mt-3 text-slate-600">{p.excerpt}</p><button className="mt-5 font-bold text-blue hover:text-gold">Read More</button></div></motion.article>)}</div> }

export function ContactSection(){ return <section id="contact" className="section bg-mist"><div className="container grid gap-8 lg:grid-cols-2"><motion.div {...fade}><p className="font-bold text-gold">Contact JST</p><h2 className="mt-2 text-3xl font-black text-navy md:text-5xl">Start your personalized travel plan</h2><div className="mt-6 space-y-3 text-slate-700"><p className="flex gap-3"><Phone className="text-gold"/> {company.phone}</p><p className="flex gap-3"><Mail className="text-gold"/> {company.email}</p><p>{company.website}</p></div><iframe title="Google Maps placeholder for Jaladhi Setu Travel" className="mt-6 h-56 w-full rounded-3xl border-0 bg-slate-200" src="about:blank"/></motion.div><motion.div {...fade} className="card"><LeadForm/></motion.div></div></section> }

export function SectionTitle({eyebrow,title,desc}:{eyebrow:string;title:string;desc?:string}){ return <div className="mx-auto mb-12 max-w-3xl text-center"><p className="font-bold text-gold">{eyebrow}</p><h2 className="mt-2 text-3xl font-black text-navy md:text-5xl">{title}</h2>{desc&&<p className="mt-4 text-slate-600">{desc}</p>}</div> }
